nedi:
    image: broadinstitute/nedi:latest
    hostname: test.example.org
    ports:
        - "80:80"
        - "443:443"
    environment:
        HTTPD_PORT: 80
        LOG_LEVEL: warn
        SERVER_ADMIN: webmaster@example.org
        SERVER_NAME: test.example.org
        SSL_HTTPD_PORT: 443
    volumes:
        - /path/to/ssl/key:/etc/ssl/private/server.key:ro
        - /path/to/ssl/certificate:/etc/ssl/certs/server.crt:ro
        - /path/to/ssl/chain:/etc/ssl/certs/ca-bundle.crt:ro
